services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_GALV_API_BASE_URL: "https://galv-demo-api.oxrse.uk"
    env_file:
      - .env.vite
    environment:
      VIRTUAL_HOST: "galv-demo.oxrse.uk"
      VITE_GALV_API_BASE_URL: "https://galv-demo-api.oxrse.uk"
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
  #    command: tail -F anything

  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      LETSENCRYPT_HOST: galv-demo.oxrse.uk
      LETSENCRYPT_EMAIL: matt.jaquiery@dtc.ox.ac.uk
      ACME_CA_URI: ${ACME_CA_URI:-https://acme-staging-v02.api.letsencrypt.org/directory}
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - static_files:/app/static
      - /home/ec2-user/certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "nginx -t" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  nginx-proxy-acme-companion:
    image: nginxproxy/acme-companion
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      LETSENCRYPT_HOST: galv-demo.oxrse.uk
      LETSENCRYPT_EMAIL: matt.jaquiery@dtc.ox.ac.uk
      ACME_CA_URI: ${ACME_CA_URI:-https://acme-staging-v02.api.letsencrypt.org/directory}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/ec2-user/certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  redis_data:
  certs:
  html:
  vhost:
  acme:
  static_files:
  redcap_data: