# SPDX-License-Identifier: BSD-2-Clause
# Copyright  (c) 2020-2023, The Chancellor, Masters and Scholars of the University
# of Oxford, and the 'Galv' Developers. All rights reserved.

FROM node:lts@sha256:132309f5136555725debd57b711eb4b329fff22a00588834dbec391a3f9782cf

RUN mkdir -p /app
WORKDIR /app
COPY . /app

RUN rm -rf /app/node_modules /app/.pnpm-store

RUN npm install -g pnpm

RUN mv .env.vite .env

RUN pnpm install
