# SPDX-License-Identifier: BSD-2-Clause
# Copyright  (c) 2020-2023, The Chancellor, Masters and Scholars of the University
# of Oxford, and the 'Galv' Developers. All rights reserved.

FROM cypress/base:20.9.0

RUN apt update && apt install -y \
    python3.9 python-is-python3 \
    build-essential \
		&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app
WORKDIR /app
COPY . /app

RUN rm -rf /app/node_modules /app/.pnpm-store

RUN npm install -g pnpm

RUN mv .env.vite .env

RUN pnpm install
