# fly.toml app configuration file generated for galv-frontend-dev on 2024-01-02T00:30:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# To launch a new deployment/manage stuff, use the pattern
# fly <command> <flags> <options> --config fly.stage.toml --app galv-frontend-stage
#
# For example, to deploy a new version of the app, use
# fly deploy --config fly.stage.toml --app galv-frontend-stage

app = "galv-frontend-stage"
primary_region = "lhr"

[build]
[build.args]
  VITE_GALV_API_BASE_URL = "https://galv-backend-stage.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
